package se.felix.controller;

import javax.validation.Valid;

//import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
//import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import se.felix.controller.ConvertForm;
//import se.felix.integration.RateRepository;

@Controller
public class Maincontroller {
	
		 			// This means to get the bean called userRepository
	//@Autowired		// Which is auto-generated by Spring, we will use it to handle the data
	//private RateRepository rateRepository;
	
	
	@GetMapping("/convert")
	public String emptyConvertSubmitted(Model model) {
		model.addAttribute("convertForm", new ConvertForm());
		return "index";
	}
	
	@PostMapping("/convert")
	public String convertSubmitted(@Valid ConvertForm convertForm, Model model) {
		
		//return rateRepository.getRate().get(0);
		/*if(bindingResult.hasErrors()) {
		 * (@Valid ConvertForm convertForm, BindingResult bindingResult, Model model)
			model.addAttribute("convertForm", new convertForm());
			//model.addAttribute("currencies", currencies);
			return "index";
		}*/
	
		//float exchanged = service.doExchange(convertForm.getFromCurrency(), convertForm.getToCurrency(), convertForm.getAmount());

		//model.addAttribute("exchanged", exchanged);
		//model.addAttribute("currencies", currencies);
		return "result";
	}
}
